#!/bin/bash

# Display system uptime
echo "System Uptime:"; uptime -p; echo

# Display CPU usage
echo "CPU Usage:"; top -bn1 | grep "Cpu(s)" | awk '{printf("  Usage: %.2f%%\n", 100 - $8)}'; echo

# Display memory usage
echo "Memory Usage:"; free -h | awk 'NR==2{printf("  Used: %s / Total: %s (%.2f%%)\n", $3, $2, $3*100/$2)}'; echo

# Display top running processes
echo "Running Processes:"; ps aux --sort=-%mem | awk 'NR<=10{printf("  %s: %s (PID: %d)\n", $1, $11, $2)}'


sync() {
mkdir -p ~/work
cd ~/work
git config --global user.name "Shravan55555"
git config --global user.email "srasidda.ks@gmail.com"
repo init -u https://github.com/PixelExperience-LEGACY-edition/manifest.git -b thirteen-plus --depth=1 --git-lfs
#git clone https://github.com/shravansayz/local_manifests.git -b derp15 .repo/local_manifests
repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune
git clone https://github.com/shravansayz/device_realme_RMX1901_13.git -b pex device/realme/RMX1901
git clone https://github.com/shravansayz/vendor_realme_RMX1901.git -b 13 vendor/realme/RMX1901
git clone https://github.com/shravansayz/kernel_realme_RMX1901_T_A13.git -b x.337_ksu kernel/realme/RMX1901
/opt/crave/resync.sh

#cd kernel/realme/sdm710 && curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5 && cd ../../..
# Auto-sign build
#rm -rf vendor/lineage-priv/keys
#wget https://raw.githubusercontent.com/Trijal08/crDroid-build-signed-script-auto/main/create-signed-env.sh
#chmod a+x create-signed-env.sh
#./create-signed-env.sh
#rm -rf .android-certs && git clone https://github.com/Legendleo90/private_keys .android-certs
#cp .android-certs/* vendor/aosp/signing/keys/
#bash <(curl -s https://raw.githubusercontent.com/Shravan55555/Signing-Script/main/keygen.sh)
#git clone https://github.com/DroidX-UI/vendor_droidx-priv_keys-template.git vendor/droidx-priv/keys
#cd vendor/droidx-priv/keys
#./gen_keys
}
echo "Syncing Rom and Device Sources..."
sync
echo "Syncing"
echo "Syncing...."
echo "Syncing......Done"
