#!/bin/bash

# Display system uptime
echo "System Uptime:"; uptime -p; echo

# Display CPU usage
echo "CPU Usage:"; top -bn1 | grep "Cpu(s)" | awk '{printf("  Usage: %.2f%%\n", 100 - $8)}'; echo

# Display memory usage
echo "Memory Usage:"; free -h | awk 'NR==2{printf("  Used: %s / Total: %s (%.2f%%)\n", $3, $2, $3*100/$2)}'; echo

# Display top running processes
echo "Running Processes:"; ps aux --sort=-%mem | awk 'NR<=10{printf("  %s: %s (PID: %d)\n", $1, $11, $2)}'


sync() {
mkdir -p ~/work
cd ~/work
git config --global user.name "Shravan55555"
git config --global user.email "srasidda.ks@gmail.com"
# Change yourUsername with your github username
wget https://raw.githubusercontent.com/Shravan55555/test/refs/heads/main/build.sh
bash build.sh
#repo init -u https://github.com/RisingOS-Revived/android -b fifteen --git-lfs
#git clone https://github.com/shravansayz/local_manifests.git -b rise .repo/local_manifests
#repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
/opt/crave/resync.sh
#cd kernel/realme/sdm710 && curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash - && curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next-susfs-4.9 && cd ../../..
#cd kernel/realme/sdm710 && curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5 && cd ../../..
# Auto-sign build
#rm -rf vendor/lineage-priv/keys
#wget https://raw.githubusercontent.com/Trijal08/crDroid-build-signed-script-auto/main/create-signed-env.sh
#chmod a+x create-signed-env.sh
#./create-signed-env.sh
#rm -rf .android-certs && git clone https://github.com/Legendleo90/private_keys .android-certs
#cp .android-certs/* vendor/aosp/signing/keys/
#bash <(curl -s https://raw.githubusercontent.com/Shravan55555/Signing-Script/main/keygen.sh)
#git clone https://github.com/DroidX-UI/vendor_droidx-priv_keys-template.git vendor/droidx-priv/keys
#cd vendor/droidx-priv/keys
#./gen_keys
}
echo "Syncing Rom and Device Sources..."
sync
echo "Syncing"
echo "Syncing...."
echo "Syncing......Done"
