#!/bin/bash

cd /tmp

# Function to compress the ccache folder
com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.xz $1
} 

# Compress ccache with compression level 1
time com ccache 1

# Upload to GoFile using upload.sh
if [ "$ROM_U" == "1" ]; then
    cd ~/work/out/target/product/$DEVICE

    # Download GoFile upload script if not already present
    wget https://github.com/Sushrut1101/GoFile-Upload/raw/master/upload.sh
    chmod +x upload.sh
    ls

    # Upload the compressed ccache archive to GoFile
    ./upload.sh /tmp/ccache.tar.xz

    # Optionally upload additional files like boot.img
    ./upload.sh boot.img
fi

